/**
 * Decap CMS — GitHub OAuth worker (Cloudflare Workers)
 * ---------------------------------------------------
 * This tiny free service lets you log into your CMS with your GitHub account.
 * You do NOT edit this file's logic. Just copy ALL of it into the Cloudflare
 * Worker editor, then set two secrets (GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET).
 * Step-by-step instructions are in SETUP-GUIDE.md (Step 6).
 */
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const { pathname, searchParams } = url;
    const origin = url.origin;
    const CLIENT_ID = env.GITHUB_CLIENT_ID;
    const CLIENT_SECRET = env.GITHUB_CLIENT_SECRET;

    // Health check
    if (pathname === "/") {
      return new Response("The Candid Duo — CMS auth worker is running ✓", {
        headers: { "content-type": "text/plain; charset=utf-8" },
      });
    }

    // 1) Kick off GitHub login
    if (pathname === "/auth") {
      if (!CLIENT_ID) return new Response("Missing GITHUB_CLIENT_ID secret", { status: 500 });
      const gh = new URL("https://github.com/login/oauth/authorize");
      gh.searchParams.set("client_id", CLIENT_ID);
      gh.searchParams.set("redirect_uri", `${origin}/callback`);
      gh.searchParams.set("scope", searchParams.get("scope") || "repo,user");
      gh.searchParams.set("state", crypto.randomUUID());
      return Response.redirect(gh.toString(), 302);
    }

    // 2) GitHub sends the user back here with a code
    if (pathname === "/callback") {
      const code = searchParams.get("code");
      if (!code) return new Response("Missing ?code", { status: 400 });
      if (!CLIENT_ID || !CLIENT_SECRET)
        return new Response("Missing GitHub client secrets", { status: 500 });

      const tokenRes = await fetch("https://github.com/login/oauth/access_token", {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "application/json",
          "user-agent": "decap-cms-oauth-worker",
        },
        body: JSON.stringify({ client_id: CLIENT_ID, client_secret: CLIENT_SECRET, code }),
      });
      const data = await tokenRes.json();

      if (data.error || !data.access_token) {
        return new Response("OAuth error: " + (data.error_description || data.error || "unknown"), {
          status: 401,
        });
      }

      const payload = JSON.stringify({ token: data.access_token, provider: "github" });
      const html =
        "<!doctype html><html><head><meta charset='utf-8'></head><body><p>Logging you in…</p><script>" +
        "(function(){" +
        "function receive(e){" +
        "window.opener.postMessage('authorization:github:success:" + payload + "', e.origin);" +
        "window.removeEventListener('message', receive, false);" +
        "}" +
        "window.addEventListener('message', receive, false);" +
        "window.opener.postMessage('authorizing:github', '*');" +
        "})();" +
        "</script></body></html>";

      return new Response(html, { headers: { "content-type": "text/html; charset=utf-8" } });
    }

    return new Response("Not found", { status: 404 });
  },
};
